(function() {var implementors = {};
implementors["compression"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.BZip2Encoder.html\" title=\"struct compression::prelude::BZip2Encoder\">BZip2Encoder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.BZip2Decoder.html\" title=\"struct compression::prelude::BZip2Decoder\">BZip2Decoder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.Inflater.html\" title=\"struct compression::prelude::Inflater\">Inflater</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.Deflater.html\" title=\"struct compression::prelude::Deflater\">Deflater</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.ZlibEncoder.html\" title=\"struct compression::prelude::ZlibEncoder\">ZlibEncoder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.ZlibDecoder.html\" title=\"struct compression::prelude::ZlibDecoder\">ZlibDecoder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.GZipEncoder.html\" title=\"struct compression::prelude::GZipEncoder\">GZipEncoder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"compression/prelude/struct.GZipDecoder.html\" title=\"struct compression::prelude::GZipDecoder\">GZipDecoder</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
